phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo "Build completed on $(date)"

  test:
    commands:
      - echo Running tests...
      - npm test -- --watchAll=false

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
